# Generated by Django 3.1.6 on 2021-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('username', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=30)),
                ('hash_pass', models.CharField(max_length=50)),
                ('claims', models.IntegerField()),
                ('complaint', models.IntegerField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
