# Generated by Django 3.1.6 on 2021-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_title', models.CharField(max_length=20)),
                ('filed_date', models.DateField(auto_now_add=True)),
                ('content', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('uploads', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
