# Generated by Django 3.1.6 on 2021-02-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimlist',
            name='status',
            field=models.CharField(choices=[('ACC', 'Accepted'), ('DEC', 'Declined'), ('NEW', 'New Claim')], default='NEW', max_length=10),
        ),
    ]
