# Generated by Django 3.1.7 on 2021-02-28 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0003_auto_20210227_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimlist',
            name='content',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='claimlist',
            name='filed_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
