# Generated by Django 3.1.7 on 2021-03-01 17:34

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0004_auto_20210227_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlist',
            name='status1',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='NEW', max_length=100, no_check_for_status=True),
        ),
    ]
