# Generated by Django 3.1.7 on 2021-03-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0005_claimlist_status1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimlist',
            name='status',
        ),
        migrations.RemoveField(
            model_name='claimlist',
            name='status1',
        ),
    ]
