# Generated by Django 3.1.7 on 2021-03-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0006_auto_20210301_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimlist',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Declined', 'Declined'), ('NEW', 'New Claim')], default='NEW', max_length=10),
        ),
    ]
