# Generated by Django 3.1.7 on 2021-03-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(default='2021-03-11'),
            preserve_default=False,
        ),
    ]
