# Generated by Django 3.1.7 on 2021-03-12 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20210311_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
    ]
